<%-- 
    Document   : license
    Created on : Dec 16, 2012, 5:59:00 PM
    Author     : admin
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@include file="header.jsp" %>
<h1>LampCMS License</h1>
<div>
 <br> 
 <br> License, TERMS and CONDITIONS
 <br> 
 <br> This software is licensed under the GNU LESSER GENERAL PUBLIC LICENSE (LGPL) version 3
 <br> Please read the license here : http://www.gnu.org/licenses/lgpl-3.0.txt
 <br>
 <br>  Redistribution and use in source and binary forms, with or without
 <br>  modification, are permitted provided that the following conditions are met:
 <br> 1. Redistributions of source code must retain the above copyright
 <br>    notice, this list of conditions and the following disclaimer.
 <br> 2. Redistributions in binary form must reproduce the above copyright
 <br>    notice, this list of conditions and the following disclaimer in the
 <br>    documentation and/or other materials provided with the distribution.
 <br> 3. The name of the author may not be used to endorse or promote products
 <br>    derived from this software without specific prior written permission.
 <br> 
 <br> ATTRIBUTION REQUIRED
 <br> 4. All web pages generated by the use of this software, or at least
 <br> 	  the page that lists the recent questions (usually home page) must include
 <br>    a link to the http://www.lampcms.com and text of the link must indicate that
 <br>    the website's Questions/Answers functionality is powered by lampcms.com
 <br>    An example of acceptable link would be "Powered by <a href="http://www.lampcms.com">LampCMS</a>"
 <br>    The location of the link is not important, it can be in the footer of the page
 <br>    but it must not be hidden by style attributes
 <br>    
 <br> THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
 <br> WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 <br> MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 <br> IN NO EVENT SHALL THE FREEBSD PROJECT OR CONTRIBUTORS BE LIABLE FOR ANY
 <br> DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 <br> (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 <br> LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
 <br> ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 <br> (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF
 <br> THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 <br> 
 <br> This product includes GeoLite data created by MaxMind, 
 <br>  available from http://www.maxmind.com/
 <br>
 <br></div>
<%@include file="/WEB-INF/pages/footer.jsp" %>
